name: Check for updates

on:
  schedule:
    # Run every day at 5.00 AM UTC
    - cron: "0 5 * * *"

jobs:
  check:
    name: Check for new versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new tags
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: make check

      # env.VERSION_TAG is set by 'Check for new tags' step

      - name: Commit and push changes (conditional)
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: dependency/${{ env.VERSION_TAG }}
          commit_message: "[AUTOMATIC] Bump for ${{ env.VERSION_TAG }}"

#      - name: Docker Lint
#        if: env.VERSION_TAG != 'null'
#        uses: luke142367/Docker-Lint-Action@v1.0.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build Docker image
#        if: env.VERSION_TAG != 'null'
#        env:
#          TERM: xterm-256color
#        run: make build

      - name: Create pull request
        if: env.VERSION_TAG != 'null'
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Bump for ${{ env.VERSION_TAG }}
          assignee: ${{ github.actor }}
          label: automatic,dependency
          template: .github/PULL_REQUEST_TEMPLATE/DEPENDENCY.md
          old_string: "<!-- Write you description here -->"
          new_string: Bump for ${{ env.VERSION_TAG }}
          get_diff: true
